# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: efd3b70c786a1715c2001afcdef3685d1f36bb05e25a299f8653adfa05a07b23711948d94ca73f557747bc07641e33666fba18afd2ab95d93ac63078af32d58c

test:
  secret_key_base: d1bd7091b5613f3389a185bdeefbd7b3eceac02da04f67e271b7ce76ac77e21db879b6d9ec3e40d049a63114db3d226fb952331278a96b35b3e555bd201978e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
