# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fd4a191793bbdd345a6a0dd74a2a83f1043793919bd7dc4c6482c3623333bd3fb53684ab9df4658dcaca8c84fb7def9e1f9f2b4260f06beb5652316aff75a49

test:
  secret_key_base: ec07cb9ff565e2308eb80beb523c991a286c1ce958387829cc4d6eaa49132f687351fffb9eaed25ab19b4f5d1d172a1e70cebebc4748c4a3665e92a9dd151bb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
